import os
import streamlit as st
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()

with st.sidebar:
    st.title("About Visa Helper")
    st.info("This AI uses real-time Google Search to provide up-to-date visa information.")
    st.markdown("### Suggested Questions:")
    st.write("- French Student Visa requirements")
    st.write("- How to book a visa appointment?")
    st.write("- Document checklist for German Schengen visa")
# Page config
st.set_page_config(page_title="Visa Helper AI", page_icon="🌎", layout="wide")

# Initialize Gemini Client
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

st.title("🌎 Visa Helper AI Support")
st.markdown("---")
# --- SESSION STATE INITIALIZATION ---
if "messages" not in st.session_state:
    st.session_state.messages = []
if "checklist" not in st.session_state:
    st.session_state.checklist = ["Passport (Valid 6+ months)", "Recent Photograph"]

# --- PDF GENERATION FUNCTION ---
def generate_pdf(items):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Visa Application Document Checklist", ln=True, align="C")
    pdf.ln(10)
    
    pdf.set_font("Helvetica", size=12)
    pdf.cell(0, 10, "Personalized roadmap based on your AI consultation:", ln=True)
    pdf.ln(5)
    
    for item in items:
        pdf.cell(0, 10, f"[ ] {item}", ln=True)
    
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 10, "Generated by Visa Helper AI Support", ln=True, align="C")
    
    return pdf.output() # This returns the PDF as a byte string

# --- SIDEBAR CHECKLIST UI ---
with st.sidebar:
    st.title("📋 Your Visa Roadmap")
    st.write("Documents identified for your application:")
    
    for item in st.session_state.checklist:
        st.checkbox(item, key=f"check_{item}")
    
    # NEW: Download PDF Button
    if st.session_state.checklist:
        pdf_data = generate_pdf(st.session_state.checklist)
        st.download_button(
            label="📄 Download Checklist as PDF",
            data=pdf_data,
            file_name="visa_checklist.pdf",
            mime="application/pdf",
            use_container_width=True
        )
    
    if st.button("Clear Checklist", use_container_width=True):
        st.session_state.checklist = ["Passport (Valid 6+ months)", "Recent Photograph"]
        st.rerun()

# --- MAIN CHAT INTERFACE ---
# (Keep the rest of your chat logic the same as the previous version)
# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat messages from history on app rerun
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# React to user input
if prompt := st.chat_input("Ask about your visa application..."):
    # Display user message in chat message container
    st.chat_message("user").markdown(prompt)
    st.session_state.messages.append({"role": "user", "content": prompt})

    try:
        with st.spinner("Searching for official visa info..."):
            # RAG Configuration with Google Search Tool
            config = types.GenerateContentConfig(
                tools=[types.Tool(google_search=types.GoogleSearch())]
            )

            # Generate response
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
                config=config
            )

            full_response = response.text
            
            # Check for grounding/sources
            if response.candidates[0].grounding_metadata:
                 full_response += "\n\n*Information verified with Google Search.*"

        # Display assistant response
        with st.chat_message("assistant"):
            st.markdown(full_response)
        
        st.session_state.messages.append({"role": "assistant", "content": full_response})

    except Exception as e:
        st.error(f"I hit a snag: {str(e)}")
