import os
import re
import streamlit as st
from google import genai
from google.genai import types
from dotenv import load_dotenv
from fpdf import FPDF

load_dotenv()

# --- 1. PAGE CONFIG (MUST BE FIRST) ---
st.set_page_config(page_title="Visa Helper AI", page_icon="🌎", layout="wide")

# --- 2. INITIALIZE CLIENT ---
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

# --- 3. SESSION STATE ---
if "messages" not in st.session_state:
    st.session_state.messages = [] 
if "history" not in st.session_state:
    st.session_state.history = []  
if "checklist" not in st.session_state:
    st.session_state.checklist = ["Passport (Valid 6+ months)", "Recent Photograph"]

# --- 4. HELPER FUNCTIONS ---
def generate_summary(history):
    if not history: return "No conversation history to summarize."
    summary_prompt = "Summarize the visa consultation above into a concise, professional one-paragraph travel plan."
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=history + [types.Content(role="user", parts=[types.Part.from_text(text=summary_prompt)])]
        )
        return response.text
    except Exception as e:
        return f"Summary failed: {str(e)}"

def generate_pdf(items):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Visa Application Document Checklist", ln=True, align="C")
    pdf.ln(10)
    pdf.set_font("Helvetica", size=12)
    pdf.cell(0, 10, "Personalized roadmap based on your AI consultation:", ln=True)
    pdf.ln(5)
    for item in items:
        pdf.cell(0, 10, f"[ ] {item}", ln=True)
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 10, "Generated by Visa Helper AI Support", ln=True, align="C")
    return bytes(pdf.output())

# --- 5. SIDEBAR UI ---
with st.sidebar:
    st.title("About Visa Helper")
    st.info("Real-time Google Search powered visa info.")
    
    st.title("📋 Your Visa Roadmap")
    for item in st.session_state.checklist:
        st.checkbox(item, key=f"check_{item}")
    
    if st.session_state.checklist:
        st.download_button(
            label="📄 Download Checklist (PDF)",
            data=generate_pdf(st.session_state.checklist),
            file_name="visa_checklist.pdf",
            mime="application/pdf",
            use_container_width=True
        )

    if st.button("📝 Summarize Consultation", use_container_width=True):
        st.info(generate_summary(st.session_state.history))

    if st.button("🔄 Start New Consultation", use_container_width=True):
        st.session_state.messages = []
        st.session_state.history = []
        st.session_state.checklist = ["Passport (Valid 6+ months)", "Recent Photograph"]
        st.rerun()

# --- 6. MAIN CHAT UI ---
st.title("🌎 Visa Helper AI Support")
st.markdown("---")

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

if prompt := st.chat_input("Ask about your visa application..."):
    st.chat_message("user").markdown(prompt)
    st.session_state.messages.append({"role": "user", "content": prompt})
    st.session_state.history.append(types.Content(role="user", parts=[types.Part.from_text(text=prompt)]))

    try:
        with st.spinner("Searching for official visa info..."):
            config = types.GenerateContentConfig(
                system_instruction="You are a professional Visa Assistant. Always enclose required documents in [brackets] like [Work ID].",
                tools=[types.Tool(google_search=types.GoogleSearch())]
            )
            
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=st.session_state.history,
                config=config
            )

            ai_response = response.text
            st.session_state.history.append(types.Content(role="model", parts=[types.Part.from_text(text=ai_response)]))
            
            # Extract new checklist items
            new_docs = re.findall(r"\[(.*?)\]", ai_response)
            for doc in new_docs:
                if doc not in st.session_state.checklist:
                    st.session_state.checklist.append(doc)

            # Build final display string
            final_display = ai_response.replace("[", "").replace("]", "")
            if response.candidates[0].grounding_metadata.search_entry_point:
                final_display += "\n\n*Information verified with Google Search.*"

        with st.chat_message("assistant"):
            st.markdown(final_display)
        
        st.session_state.messages.append({"role": "assistant", "content": final_display})
        st.rerun()

    except Exception as e:
        st.error(f"I hit a snag: {str(e)}")
